Fixed/revised f7a26aeab132d7e8c29d7a4cc3b7a25f3960278a.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -38,33 +38,34 @@ script:
     make -e ${MAKEJ} ${PEDANTIC_HIGH} AVX=2 THREADS=0 ECXXFLAGS='-DUSE_HEADER_ONLY' compile &&
     make -e ${MAKEJ} ${PEDANTIC_HIGH} AVX=1 VLA=0 ECXXFLAGS='-DUSE_HEADER_ONLY' compile
 
-  - if [ "${STATIC_ANALYSIS}" ] && [ "0" = "${STATIC_ANALYSIS}" ]; then
+  - if [ "${STATIC_ANALYSIS}" ] && [ "0" != "${STATIC_ANALYSIS}" ]; then
       ${TRAVIS_BUILD_DIR}/scripts/tool_analyze.sh;
     fi
 
-  - if [ "${STATIC_ANALYSIS}" ] && [ "0" = "${STATIC_ANALYSIS}" ]; then
+  - if [ "${STATIC_ANALYSIS}" ] && [ "0" != "${STATIC_ANALYSIS}" ]; then
       ${TRAVIS_BUILD_DIR}/scripts/tool_normalize.sh;
     fi
 
-  - if [ "${STATIC_ANALYSIS}" ] && [ "0" = "${STATIC_ANALYSIS}" ]; then
+  - if [ "${STATIC_ANALYSIS}" ] && [ "0" != "${STATIC_ANALYSIS}" ]; then
       make -e ${MAKEJ} STATIC=0 DBG=1 && ${TRAVIS_BUILD_DIR}/scripts/tool_checkabi.sh;
     fi
 
-  - if [ ! "${STATIC_ANALYSIS}" ] || [ "0" = "${STATIC_ANALYSIS}" ]; then exit 0; fi;
-    if [ ! "${COVERITY_SCAN_BINDIR}" ] || [ ! "${COVERITY_SCAN_USER}" ] || [ ! "${COVERITY_SCAN_TOKEN}" ]; then
-      echo "Please setup COVERITY_SCAN_BINDIR, COVERITY_SCAN_USER, and COVERITY_SCAN_TOKEN.";
-      exit 1;
-    fi;
-    if [ "${COVERITY_SCAN_TMPDIR_CLEAR}" ] && [ "0" != "${COVERITY_SCAN_TMPDIR_CLEAR}" ] &&
-       [ "." != ""${COVERITY_SCAN_TMPDIR}"" ] && [ -e "${COVERITY_SCAN_TMPDIR}" ];
-    then
-      rm -rf "${COVERITY_SCAN_TMPDIR}";
-    fi;
-    ${COVERITY_SCAN_BINDIR}/cov-build --dir ${COVERITY_SCAN_TMPDIR} make -e ${MAKEJ} &&
-    tar cvfz "${COVERITY_SCAN_TGZDIR}/cov-int.tgz" -C "$(dirname "${COVERITY_SCAN_TMPDIR}")" --transform
-      "s/^$(basename "${COVERITY_SCAN_TMPDIR}")/cov-int/" $(basename ${COVERITY_SCAN_TMPDIR}) &&
-    curl https://scan.coverity.com/builds?project=hfp-libxsmm --form
-      token=${COVERITY_SCAN_TOKEN} --form email=${COVERITY_SCAN_USER} --form
-      file=@${COVERITY_SCAN_TGZDIR}/cov-int.tgz --form
-      version="$(${TRAVIS_BUILD_DIR}/scripts/libxsmm_version.sh)" --form
-      description="$(date -I): $(git log -1 --pretty=oneline | cut -d' ' -f2-)"
+  - if [ "${STATIC_ANALYSIS}" ] && [ "0" != "${STATIC_ANALYSIS}" ]; then
+      if [ ! "${COVERITY_SCAN_BINDIR}" ] || [ ! "${COVERITY_SCAN_USER}" ] || [ ! "${COVERITY_SCAN_TOKEN}" ]; then
+        echo "Please setup COVERITY_SCAN_BINDIR, COVERITY_SCAN_USER, and COVERITY_SCAN_TOKEN.";
+        exit 1;
+      fi;
+      if [ "${COVERITY_SCAN_TMPDIR_CLEAR}" ] && [ "0" != "${COVERITY_SCAN_TMPDIR_CLEAR}" ] &&
+         [ "." != ""${COVERITY_SCAN_TMPDIR}"" ] && [ -e "${COVERITY_SCAN_TMPDIR}" ];
+      then
+        rm -rf "${COVERITY_SCAN_TMPDIR}";
+      fi;
+      ${COVERITY_SCAN_BINDIR}/cov-build --dir ${COVERITY_SCAN_TMPDIR} make -e ${MAKEJ} &&
+      tar cvfz "${COVERITY_SCAN_TGZDIR}/cov-int.tgz" -C "$(dirname "${COVERITY_SCAN_TMPDIR}")" --transform
+        "s/^$(basename "${COVERITY_SCAN_TMPDIR}")/cov-int/" $(basename ${COVERITY_SCAN_TMPDIR}) &&
+      curl https://scan.coverity.com/builds?project=hfp-libxsmm --form
+        token=${COVERITY_SCAN_TOKEN} --form email=${COVERITY_SCAN_USER} --form
+        file=@${COVERITY_SCAN_TGZDIR}/cov-int.tgz --form
+        version="$(${TRAVIS_BUILD_DIR}/scripts/libxsmm_version.sh)" --form
+        description="$(date -I): $(git log -1 --pretty=oneline | cut -d' ' -f2-)";
+    fi
